# Generated by Django 5.0.4 on 2024-05-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='ФИО')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Вы',
                'verbose_name_plural': 'Вы',
            },
        ),
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailLogin', models.CharField(max_length=255, verbose_name='Логин')),
                ('mailPassword', models.CharField(max_length=255, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активно')),
                ('mailSmtpServer', models.CharField(max_length=255, verbose_name='SMTP сервер')),
                ('mailSmtpPort', models.IntegerField(default=465, verbose_name='SMTP порт')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Почтовое оповещение',
                'verbose_name_plural': 'Почтовое оповещение',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.TextField(verbose_name='Компания')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('dateStart', models.DateField(verbose_name='Начало')),
                ('dateEnd', models.DateField(verbose_name='Конец')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduName', models.TextField(verbose_name='Учебн. учреждение')),
                ('eduDepartment', models.TextField(verbose_name='Факультет')),
                ('eduQualification', models.TextField(verbose_name='Квалификация')),
                ('dateStart', models.DateField(verbose_name='Начало')),
                ('dateEnd', models.DateField(verbose_name='Конец')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('github', models.TextField(verbose_name='Github')),
                ('telegram', models.TextField(verbose_name='Telegram')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projName', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('photo', models.ImageField(upload_to='photos/projects', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skiName', models.TextField(verbose_name='Наименование навыка')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
