# Generated by Django 5.0.6 on 2024-06-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Вы',
                'verbose_name_plural': 'Вы',
            },
        ),
        migrations.CreateModel(
            name='Site_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.TextField(verbose_name='Имя сайта')),
                ('previewS', models.TextField(verbose_name='Превью статический текст')),
                ('previewD', models.TextField(verbose_name='Превью динамический текст')),
                ('footerText', models.TextField(verbose_name='Текст футера')),
            ],
        ),
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailLogin', models.CharField(max_length=255, verbose_name='Логин')),
                ('mailPassword', models.CharField(max_length=255, verbose_name='Пароль')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активно')),
                ('mailSmtpServer', models.CharField(max_length=255, verbose_name='SMTP сервер')),
                ('mailSmtpPort', models.IntegerField(default=465, verbose_name='SMTP порт')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Почтовое оповещение',
                'verbose_name_plural': 'Почтовое оповещение',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(verbose_name='Компания')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('info', models.TextField(verbose_name='Обязанности')),
                ('dateStart', models.DateField(verbose_name='Начало')),
                ('dateEnd', models.DateField(verbose_name='Конец')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Учебн. учреждение')),
                ('department', models.TextField(verbose_name='Факультет')),
                ('info', models.TextField(verbose_name='Что освоили')),
                ('dateStart', models.DateField(verbose_name='Начало')),
                ('dateEnd', models.DateField(verbose_name='Конец')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('github', models.TextField(verbose_name='Github')),
                ('telegram', models.TextField(verbose_name='Telegram')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('policy', models.TextField(verbose_name='Политика конфиденциальности')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projName', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('desc', models.TextField(verbose_name='Описание проекта')),
                ('tech', models.TextField(verbose_name='Используемые технологии')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/projects', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.TextField(verbose_name='Бэкенд')),
                ('frontend', models.TextField(verbose_name='Фронтенд')),
                ('linux', models.TextField(verbose_name='ПО Линукс')),
                ('windows', models.TextField(verbose_name='ПО Виндовс')),
                ('databases', models.TextField(verbose_name='Базы данных')),
                ('virtualization', models.TextField(verbose_name='Виртуализация')),
                ('softskills', models.TextField(verbose_name='СофтСкиллс')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.person')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
