# Generated by Django 5.0.4 on 2024-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='eduDepartment',
            field=models.TextField(default='IT'),
        ),
        migrations.AddField(
            model_name='education',
            name='eduQualification',
            field=models.TextField(default='IT'),
        ),
    ]
