# Generated by Django 5.0.4 on 2024-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.TextField(null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduDepartment',
            field=models.TextField(null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduQualification',
            field=models.TextField(null=True, verbose_name='Квалификация'),
        ),
    ]
