# Generated by Django 5.0.6 on 2024-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_settings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='backend',
            field=models.TextField(blank=True, verbose_name='Бэкенд'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='databases',
            field=models.TextField(blank=True, verbose_name='Базы данных'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='frontend',
            field=models.TextField(blank=True, verbose_name='Фронтенд'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='linux',
            field=models.TextField(blank=True, verbose_name='ПО Линукс'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='softskills',
            field=models.TextField(blank=True, verbose_name='СофтСкиллс'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='virtualization',
            field=models.TextField(blank=True, verbose_name='Виртуализация'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='windows',
            field=models.TextField(blank=True, verbose_name='ПО Виндовс'),
        ),
    ]
