# Generated by Django 5.0.4 on 2024-05-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailLogin', models.CharField(max_length=255, verbose_name='Логин')),
                ('mailPassword', models.CharField(max_length=255, verbose_name='Пароль')),
                ('preson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
