# Generated by Django 5.0.4 on 2024-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_edudepartment_education_eduqualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Вы', 'verbose_name_plural': 'Вы'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterField(
            model_name='education',
            name='dateEnd',
            field=models.DateField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='education',
            name='dateStart',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduDepartment',
            field=models.TextField(default='IT', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduName',
            field=models.TextField(verbose_name='Учебн. учреждение'),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduQualification',
            field=models.TextField(default='IT', verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='comName',
            field=models.TextField(verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='dateEnd',
            field=models.DateField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='dateStart',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='post',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projName',
            field=models.CharField(max_length=255, verbose_name='Имя проекта'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skiName',
            field=models.TextField(verbose_name='Наименование навыка'),
        ),
    ]
