# Generated by Django 5.0.6 on 2024-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_site_settings_options_alter_skills_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='backend',
            field=models.TextField(blank=True, null=True, verbose_name='Бэкенд'),
        ),
    ]
