# Generated by Django 5.0.4 on 2024-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contacts_phone_alter_contacts_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Санкт-Петербург', max_length=255, verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/projects', verbose_name='Фото'),
        ),
    ]
