# Generated by Django 5.0.4 on 2024-05-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailnotification_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailnotification',
            options={'verbose_name': 'Электранная почта', 'verbose_name_plural': 'Электронные почты'},
        ),
    ]
