# Generated by Django 5.0.6 on 2024-06-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skills_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='main.person'),
        ),
    ]
