# Generated by Django 5.0.6 on 2024-06-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skills_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to='main.person'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='main.person'),
        ),
    ]
